sudo: required
language: node_js
node_js:
  - "0.10"

cache:
  directories:
  - node_modules
  - $HOME/.yarn-cache

install:
  - npm install

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - ./node_modules/.bin/karma start karma.conf.js --single-run

after_script:
  - cat ./coverage/karma/**/*.info > lcov.info
  - cat lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage

addons:
  firefox: 'latest'
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
