sudo: required
language: node_js
node_js:
  - "6"
  - "4"

addons:
  firefox: 'latest'
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

cache:
  directories:
  - node_modules
  - $HOME/.yarn-cache

before_install:
  - npm install -g yarn --cache-min 999999999

install:
  - yarn

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - rm dist/*
  - ./node_modules/.bin/gulp

after_script:
  - cat .coverage/karma/**/*.info > lcov.info
  - cat lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
